### PR TITLE
Version 0.1.0

### PR DESCRIPTION
**Pull request by guseggert**

### CODE REVIEW

**Review by petar — APPROVED** [review]

**Review by marten-seemann — CHANGES_REQUESTED** [review]
I don't think this repo needs to be updated. There are no code changes.

**Comment by guseggert** [comment]
Are there any downsides to updating these anyway?

**Comment by marten-seemann** [comment]
Other than creating churn, probably not.

**Comment by guseggert** [comment]
Sorry I missed that this _does_ have code changes, it is releasing this commit: https://github.com/ipfs/go-ipfs-exchange-offline/commit/6ef3e0ac8dfd20522c918e1eb6f8ac07cec41bd1

**Review by marten-seemann — APPROVED** [review]

**Pull request merged**
